language: node_js
node_js:
- lts/*
before_script:
- npm install
notifications:
  email:
    on_success: always
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
env:
  global:
  - DOCKER_USER=kiwihannah
services:
  - docker