name: mini

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: if fail
        uses: actions/checkout@v2
        with:
          github-token: ${{github.token}}
          script: |
            github-token: ${{github.token}} 
              script: |
                const ref = "${{github.ref}}"
                const pull_number = Number(ref.split("/")[2])
                await github.pulls.createReview({
                  ...context.repo,
                  pull_number,
                  body:"테스트코드를 다시 확인해주세요. ",
                  event: "REQUEST_CHANGES"
                })
                await github.pulls.update({
                  ...context.repo,
                  pull_number,
                  state: "closed"
                })
          if: failure()
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/mini
            sudo npm install
            sudo git pull
            sudo pm2 reload all
