name: mini

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node 
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm install

      - name: Run tests 
        run: npm test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results
          path: ${{ github.workspace }}/reports/test-results.json
          fail-on-error: 'false'
          reporter: 'mocha-json'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/mini
            sudo git pull
            sudo pm2 reload all
            
      - name: Slack Notifications
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: '테스트 망했으니까 로그 좀 봐'
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()